### ISSUE TITLE
AUR install fails

### ISSUE THREAD

**Issue by TimotheeMathieu** [steven-omaha/pacdef#10]
**Describe the bug**
When I try to install pacdef via AUR with yay, it fails.
I installed it using pip install from cloned repo and it works great.

**Affected version**
Output of `pacdef version`: na

Output of `python --version`: Python 3.10.8

**Operating System**

Arch-Linux

**To Reproduce**
1. `yay -S pacdef`

**Expected behavior**
pacdef installs

**Logs and outputs**

```
________________________________________ ERROR collecting tests/test_aur_helper.py _________________________________________
ImportError while importing test module '/home/user/.cache/yay/pacdef/src/pacdef-0.8.0/tests/test_aur_helper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_aur_helper.py:10: in <module>
    from tests.constants import PACMAN, PACMAN_EXISTS, REASON_NOT_ARCH
E   ModuleNotFoundError: No module named 'tests.constants'
__________________________________________ ERROR collecting tests/test_pacdef.py ___________________________________________
ImportError while importing test module '/home/user/.cache/yay/pacdef/src/pacdef-0.8.0/tests/test_pacdef.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_pacdef.py:16: in <module>
    from test_aur_helper import TestAURHelper
tests/test_aur_helper.py:10: in <module>
    from tests.constants import PACMAN, PACMAN_EXISTS, REASON_NOT_ARCH
E   ModuleNotFoundError: No module named 'tests.constants'
================================================= short test summary info ==================================================
ERROR tests/test_aur_helper.py
ERROR tests/test_pacdef.py
```

**Comment by steven-omaha** [comment]
Thanks for the report! I cannot investigate this right now. Please let me know if the issue persists if you install it by cloning a fresh copy from the AUR and running `makepkg -sfi`

**Comment by TimotheeMathieu** [comment]
I tried and yes, with a fresh copy from AUR and `makepkg -sfi` the problem is still there.

**Comment by arctic-penguin** [comment]
I will probably get back to you with a fix in the new year.

**Comment by steven-omaha** [comment]
I will probably get back to you with a fix in the new year.

**Comment by steven-omaha** [comment]
I cannot reproduce the error using the following.

```
git clone https://aur.archlinux.org/pacdef.git
cd pacdef
makepkg -sf
```

Do you use a custom pip configuration by chance? Have you set any python-related environment variables?

**Comment by TimotheeMathieu** [comment]
I checked and you are right, it works on a clean arch install (I used qemu on the last arch iso).

I don't have a custom pip configuration (anyway the install via pip works it is only the install via aur that does not work for me). The only python-related environment variable that I have is `PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` which should not be a problem I think.

**Comment by steven-omaha** [comment]
Then I don't really know what could cause this error. Other things you could check are flags in `makepkg.conf`, and
whether your `pytest` is up-to-date. Otherwise I can only close this as not reproducible.

**Comment by TimotheeMathieu** [comment]
Ok, I finally found where is a problem. I have a library in `site-packages` called "tests" which was conflicting with your imports of the folder `tests` for pytest. Now that it is uninstalled everything is working fine ! 
So I close.
