### ISSUE TITLE
Option to skip confirmation for sync/clean actions

### ISSUE THREAD

**Issue by ironashram** [steven-omaha/pacdef#13]
First of all, great tool, i find it extremely useful.

My goal would be to use pacdef as base for a fully automated pipeline which installs or removes packages in a set of devices when a definition is updated in a vcs repository.

The only thing stopping me is the interactive confirmation prompt, would you consider adding an option to make it unattended? 

Eventually i could give it a go and open a PR, but i wanted to ask before hand, also considering i saw you started working on a rust version, anyway, let me know.

**Comment by ironashram** [comment]
>Having something like --noconfirm for clean and sync is definitely possible. You probably would want to propagate that to the AUR helper, right?

Indeed

>It's not going to be implemented in the Python version, but I will do it in Rust. The Rust remake is about ready.

Sounds great thank you

**Comment by steven-omaha** [comment]
Fixed in reimplementation.
