### ISSUE TITLE
Option to suppress symlink warnings

### ISSUE THREAD

**Issue by ostrich** [steven-omaha/pacdef#14]
Really nice utility you've created. Looking forward to the Rust rewrite mentioned in #13.

I use pacdef with [chezmoi](https://github.com/twpayne/chezmoi) to sync my group definitions. Since chezmoi best practice isn't to use symlinks, I get lots of warnings. It would be nice to be able to suppress them. That's all 😁

**Comment by steven-omaha** [comment]
That option already exists, but is undocumented.

Set the following in your config.

```
[misc]
warn_not_symlink = false
```
