### ISSUE TITLE
add flatpak support

### ISSUE THREAD

**Issue by araruna** [steven-omaha/pacdef#17]
I loved the idea of this tool, and I'd use it a lot, but the problem is that I depend on some flatpak packages.

Is it feasible / planned to add support for it?

Thanks

**Comment by steven-omaha** [comment]
I have never used flatpak. Am I understanding correctly that for the user it would behave like a package manager, and allows installing static binaries?

**Comment by sintaulsiam** [comment]
Flatpak support would be good

**Comment by sintaulsiam** [comment]
> I have never used flatpak. Am I understanding correctly that for the user it would behave like a package manager, and allows installing static binaries?

Flatpak is a containerize universal package format for linux

**Comment by steven-omaha** [comment]
@sintaulsiam Could you please link to an example that shows how you would install a flatpak package on your Linux?

**Comment by sintaulsiam** [comment]
https://docs.flatpak.org/en/latest/using-flatpak.html

**Comment by steven-omaha** [comment]
Thanks! 

I'm not using flatpak and do not intend doing so in the near future, because my needs are covered. Adding support would definitely be possible. I'm just looking for someone to implement it and come up with a PR.

**Comment by steven-omaha** [comment]
That being said: If anyone of you knows a bit of rust and would like to give it a shot, let me know. @sintaulsiam @araruna

**Comment by araruna** [comment]
> That being said: If anyone of you knows a bit of rust and would like to give it a shot, let me know. @sintaulsiam @araruna 

I might try it, but I cannot commit to it at this moment.

I'll look into the code and give it a go when I'm available.

**Comment by steven-omaha** [comment]
Great! Let me know when you have questions.

**Comment by teackot** [comment]
Hi! I'm also interested in a flatpak backend. I just started working on it in my draft PR.

**Comment by steven-omaha** [comment]
That's great! Let me know if you have any questions.

**Comment by steven-omaha** [comment]
Implemented by #20. Thank you @teackot!

@araruna @sintaulsiam  If you want to give it a try, you can install `pacdef-git` if you are on Arch, or clone this repo and install it from HEAD. I will make a release in the next days.
