### ISSUE TITLE
missing privilege escalation under Debian

### ISSUE THREAD

**Issue by Zaubentrucker** [steven-omaha/pacdef#24]
I've installed pacdef on a fresh Ubuntu VM. 
If I specify packages for `[debian]`, I get the following:

```bash
zaubentrucker@pita-ubuntu:~$ pacdef package sync
WARNING: group file /home/zaubentrucker/.config/pacdef/groups/base is not a symlink
Would install the following packages:

[debian]
lolcat

[rust]
fd-find

Continue? [Y/n] 
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Error: running action

Caused by:
    0: installing packages
    1: command returned with exit code 100
```

This makes sense, since `apt` needs root rights for installing packages.
If I execute pacdef as root, it can't find my group files anymore and would probably fail trying to install packages through cargo as well.

Am I just not using the tool in the right way?
Or should pacdef try to acquire root rights if `apt` is called?

**Comment by steven-omaha** [comment]
Thanks for the report! That's definitely a bug. I don't have a Debian machine that supports the rust bindings for apt, so I couldn't test it thoroughly.

What happens when you run `sudo -E pacdef package sync` as your local user?

**Comment by steven-omaha** [comment]
If that does not work, I will probably need to add privilege escalation if the EUID is not zero.

**Comment by steven-omaha** [comment]
I will get back to you with a fix, hopefully by Friday.

**Comment by steven-omaha** [comment]
@Zaubentrucker Could you please try out the fix? It's working on my end already.

```
$ git clone https://github.com/steven-omaha/pacdef
$ cd pacdef
$ git checkout devel
$ cargo run -F debian -- group new --edit base
$ cargo run -F debian -- package sync
```

**Comment by Zaubentrucker** [comment]
This works for me :+1: 
Thank you for the fix!

You will probably need to do the same for snap, if you want to support it.
