### ISSUE TITLE
properly handle imported group folders

### ISSUE THREAD

**Issue by Byter09** [steven-omaha/pacdef#27]
Hi! Love the tool. I tried to create a `pacdef` folder in my personal vault (so my definitions get backed up properly) and then used `pacdef group import`.

`~/.config/pacdef/groups` now contains all my files as symlinks, which is perfect, however, because I use folders similar to the setup described in the readme, I now also get this error:

```
❯ pacdef group list
Error: loading groups under /home/btr/.config/pacdef/groups

Caused by:
    0: reading group file "/home/btr/.config/pacdef/groups/generic"
    1: reading file content
    2: Is a directory (os error 21)
```

I see three solutions for this:
1. ignore folders when traversing down
2. so you can have group files with the same name in different folders, make the group symlink a concatenated list of all folders down to the file. So the group file `groups/generic/base` would become a  `generic_base` symlink.
3. a combination of 1. and 2.: simply symlink one-to-one and ignore folder symlinks when traversing

**Comment by steven-omaha** [comment]
Thanks for the report! Will look into it when I have the time.

**Comment by steven-omaha** [comment]
@Byter09 I see that you have a bit of experience in coding Rust. Would you like to give it a try? I could coach you when you have any question. I can also give you pointers on how the solution could work.

**Comment by Byter09** [comment]
I professionally work with Rust and most of my stuff is on GitLab, so not a lot to see on my GitHub profile. Thanks to the profession part I rarely have free time to work on things that aren't *my* projects, if that makes sense. Hope you don't feel like I was "dumping" this issue on you. I got a lot on my plate already, sorry. :/

**Comment by steven-omaha** [comment]
@Byter09 I have implemented this in the `devel` branch. Feel free to try it out and let me know if this works.

**Comment by Byter09** [comment]
Awesome. I will probably give this a try tomorrow. I currently have `pacdef` installed via `paru`, so I'll have to switch to cargo etc. Gives me a chance to also extend my group files a bit. Got stopped out when I ran into this issue in the first place.

Thanks for working on this so quickly.

**Comment by Byter09** [comment]
So, I tried the import again, and it works as before, but I'm now greeted by this:
```
WARNING: group file /home/btr/.config/pacdef/groups/hosts/server is not a symlink
```
So for some reason it's symlinking the directories, but not the files.

**Comment by steven-omaha** [comment]
Please ignore the warning for now. (you can disable that in the config, see the README).

If you add a package to any of the sections in `server`, is it recognized?

**Comment by Byter09** [comment]
Just tried it by adding `htop` under `arch` and running `pacdef group show hosts/server`, which results in the known warnings and 
```
[arch]
htop
```
as output. So seems to work :D

**Comment by steven-omaha** [comment]
That's great. Thanks for confirming!

The command is supposed to import anything by creating a symlink to it. If it is a directory, it traverses it. The symlink warning is just not updated yet, because if I import a directory that contains a file somewhere (possibly many levels deep), I need to track if any of the files' ancestors is a symlink. That's just not implemented yet.

Closing this as completed for now. Will fix the warning later.

**Comment by Byter09** [comment]
Okay the problem here is that its not just the warning that is the problem. The files it imported are actual files. The only symlinks I see are the directories. 
![grafik](https://github.com/steven-omaha/pacdef/assets/16060697/b7fc8994-da4f-4f9c-98f6-a2b210972a2e)

**Comment by steven-omaha** [comment]
That is how I implemented it. Is that not what you wanted?

**Comment by Byter09** [comment]
Oh I figured it would also symlink those files, so I can modify my files inside the actual folder they're in. This would be useful if you have them somewhere else (like a vault) for backup or git purposes.

**Comment by Byter09** [comment]
If that's a separate issue I will open one if you want. I am already happy about the folder traversal :D

**Comment by steven-omaha** [comment]
I'm not quite following. 

Let's say I have a pacdef repository like in the README. In the outermost dir, I run `pacdef group import generic`. This creates a symlink from `~/.config/pacdef/groups/generic` to `./generic`. Then any edit I make under either the group dir or the pacdef repository is reflected in both locations. 

What am I missing?

**Comment by Byter09** [comment]
Oh my god, sorry I just didn't have caffeine yet. It just _looks_ like a file because it links to the actual file. I somehow thought you'd need a symlink per file. Please disregard haha. Thank you! :D
