### ISSUE TITLE
AUR installation does not include `pacdef_core`

### ISSUE THREAD

**Issue by philpax** [steven-omaha/pacdef#43]
Hi there!

I am trying to install `pacdef` through the AUR (specifically, `paru`), but it fails as `pacdef_core` is not included:
```
error: no matching package named `pacdef_core` found
location searched: registry `crates-io`
required by package `pacdef v1.3.0 (/home/philpax/.cache/paru/clone/pacdef/src/pacdef-1.3.0)`
```

Looking into it, this appears to be because the AUR pkgbuild downloads the `pacdef` crate from `crates.io`, which does not include `crates/pacdef_core`.

I'd suggest changing `pacdef`'s `Cargo.toml` to point at a published version of `pacdef_core`; [the publish process will only use the published version of the crate](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations), which should allow you to develop and publish versions at the same time. (With the caveat that you'll need to use something like `cargo release` to publish all of the crates at the same time.)

**Comment by steven-omaha** [comment]
Thanks for the report.  I cannot reproduce it. Both 
```
paru -S pacdef
```
and
```
paru -G pacdef
cd pacdef
makepkg
```
work.

**Comment by philpax** [comment]
Bah, it was an issue with my system. I hadn't updated Rust in a while, and it looks like whatever version of Rust I was on wasn't resolving packages properly. Updating to the latest fixed it.

Thanks for poking me to look into it more closely!
