### ISSUE TITLE
Group dependencies

### ISSUE THREAD

**Issue by thcrt** [steven-omaha/pacdef#46]
It would be really cool to have one list be dependent on another. Different files could also satisfy the same dependency. For instance, `desktop` could depend on `audio` as well as one of `[plasma, gnome, sway]` where `sway` is itself dependent on `wayland`.

**Comment by steven-omaha** [comment]
Thanks for the suggestion. That's an interesting point that I have not thought about yet. Will get back to you. If you don't hear from me within a week, please feel free to leave a reminder here. Thank you.

**Comment by steven-omaha** [comment]
@thcrt I think I see the value behind this suggestion. I'd still prefer not to implement this. I would like for pacdef to keep following the KISS principle and rather follow the original Unix philosophy of "doing one thing and doing it well". 

It should be easy to come up with a tool that sits on top of pacdef and does what you suggest. Or you could even use a dotfiles manager.

Still, thank you for the suggestion.

**Comment by thcrt** [comment]
Thank you for the well-reasoned reply :) I also see where you're coming from. Thanks also for your work on this really nice tool <3
