### ISSUE TITLE
Add support for pipx?

### ISSUE THREAD

**Issue by InnocentZero** [steven-omaha/pacdef#48]
Hello, is it possible to add support for pipx installation utility? It is the recommended method to install python executables that are not available in the default repositories or in AUR. 

Thanks a lot!

**Comment by steven-omaha** [comment]
Hey, thanks for the report. I'm unfamiliar with `pipx`. Is that a replacement for `pip`?

**Comment by InnocentZero** [comment]
TL,DR: pipx manages and maintains virtual environments for python projects so that they do not cause conflicts with the system packages and allow users to run python programs. Mostly invoked via `$ pipx install spotdl` (notice the command is run as user).

From the archwiki page

> pipx — Closely related to pip, but creates, for the user running it, an isolated environment for each application and its associated packages, preventing conflicts with system packages. Focused on packages that can be run from the command line directly as applications. You can use pipx to install packages from the [Python Package Index](https://pypi.org/) and other indexes.

When you try to execute `pip install executable` in arch, this is the error message:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by steven-omaha** [comment]
So for the user `pipx` acts as kind of substitute for `pip`, and creates separate environments for whatever the user wants to have installed. Do I have that correct? 

> If possible,I'd like to contribute this feature myself if you can guide me through the code. 

That would be great, and highly appreciated!

If my understanding is correct, then the solution would be the following.
1. Create a config value in `Config` where we can specify in the config file which binary we would like to use (pip or pipx). The default should be `pip`.
https://github.com/steven-omaha/pacdef/blob/ec1aab4b432df764e26f379a179c435670d778a4/crates/pacdef_core/src/config.rs#L11-L26 
2. Depending on the binary, the backend must use different calls. For example for  `pip` I use `pip list --format json`, but the json format is not available for pipx. For `pipx` we could just check the folders in `~/.local/share/pipx/venvs`. Or rather, use `$XDG_DATA_HOME/.pipx/venvs`. For how we get `XDG_DATA_HOME`, take a look at `pacdef_core::path::get_xdg_config_home()`.
3. Make `struct Python` in `python.rs` remember which binary we want to use, and then decide which calls to use. You would want a `binary` field like in `struct Arch`.
4. Make `pacdef_core::Pacdef::overwrite_values_from_config(...)` apply the config value to the backend. 

Then everything should work.

Feel free to open a WIP PR, and also to request reviews often. I'm very happy to help, and don't mind giving feedback often. But it is up to you how much or little input you would like, of course.

**Comment by InnocentZero** [comment]
> So for the user pipx acts as kind of substitute for pip, and creates separate environments for whatever the user wants to have installed. Do I have that correct?

Yes. That is the primary reason I believe.

> Feel free to open a WIP PR, and also to request reviews often. I'm very happy to help, and don't mind giving feedback often. But it is up to you how much or little input you would like, of course.

I'll do so. Appreciate your guidance. Should I use the PR to discuss suggestions or this issue thread?

**Comment by steven-omaha** [comment]
Let's discuss any implementation details in the PR. 

Thanks for your willingness to help!

**Comment by InnocentZero** [comment]
See #50
