### ISSUE TITLE
panic in python.rs in version 1.4.0

### ISSUE THREAD

**Issue by cjhardekopf** [steven-omaha/pacdef#52]
When trying to run: `pacdef p sy` I get a panic:

```
thread 'main' panicked at /.../pacdef_core-1.4.0/src/backend/actual/python.rs:80:18:
Cannot use  for package management in python. Please use a valid package manager like pip or pipx.
```

It looks like the python binary is defaulting to an empty string instead of a valid value. I fixed the panic by putting:

```
pip_binary: 'pipx'
```

in my `pacdef.yaml`. However, I would have thought that it would have a reasonable default.

**Comment by steven-omaha** [comment]
Thanks for the report! Yes, there should be a default value (ideally pip, since pipx is not available everywhere).

@InnocentZero would you like to fix this? Otherwise I could do it.

**Comment by InnocentZero** [comment]
Oh, I'm sorry for this. I thought I took care of this but I seemed to have missed it. I'll push a fix ASAP.
