### ISSUE TITLE
Add support for rustup/npm/yarn etc?

### ISSUE THREAD

**Issue by InnocentZero** [steven-omaha/pacdef#54]
Hi, it's me again. I was wondering just how many package managers have been considered to be eventually supported by the project before, and if you intend to add more to the list, I'm happy (and more importantly free atm) to add support for rustup, npm, yarn, and a few others.

I'd like to start with rustup, since it seems the most straightforward to me. Or are there any alternative suggestions?

**Comment by steven-omaha** [comment]
Hey there, thanks for your support and motivation! I'm open for absolutely anything. I'm okay if pacdef were to support all the backends. 

What would you like to manage in rustup? Let's talk a bit about what you have envisioned.

Personally I do not use npm and yarn, so I cannot help you there, and have no opinion about what should or shouldn't be done. Feel free to tackle that if you'd like. 

And let's focus on rustup for the time being, as you suggested.

**Comment by InnocentZero** [comment]
Coming from personal experience, I really liked the idea of NixOs and its declarative package management and this project lets me have the best of it without the headache of learning an entirely new programming language just to manage my packages from a file.

As for rustup, I had switched machines before this and since rustup components and toolchains aren't exactly what you'd use every day, it took me quite some time to (re)-learn out how (and what) to add the components and toolchains just to compile eww (thanks to its non-standard toolchain preference). 

The main idea behind managing rustup components and toolchains is to be able to exactly replicate the toolchain behaviour on another machine so that any rust developer does not need to waste time when let's say upgrading their linux-box hardware and reinstalling everything.

For npm, apart from the above argument, you can also install executables, which I did back when I was on fedora.

**Comment by InnocentZero** [comment]
I think there is a slight problem with this. Components are added for specific toolchains and not just for everything. Someone running multiple toolchains might not want to have, say miri for every toolchain. So I think something like 


```
[rustup]
toolchain/stable
toolchain/nightly
component/nightly/rust-analyzer
```

might be more suited.

**Comment by steven-omaha** [comment]
Makes sense. Then we need to rework `Package`, but I'm not sure yet how much. Let's figure it out together. 

Feel free to open a WIP PR.

**Comment by steven-omaha** [comment]
Github was a bit overeager with closing this automatically.

**Comment by InnocentZero** [comment]
Hi, long time. I'd just like to mention that an npm backend will soon be in work. Unfortunately real life was/is being a bit demanding rn, so newer backends couldn't be implemented.
