### ISSUE TITLE
libalpm.so.13: cannot open shared object file

### ISSUE THREAD

**Issue by gro-david** [steven-omaha/pacdef#57]
`pacdef: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory`

Since yesterday this is happening any time I want to run pacdef. Before that nothing like this would ever occur.

**Comment by szczerbowski** [comment]
Same here on vanilla Archlinux.

**Comment by steven-omaha** [comment]
Thanks for the report, will get to it hopefully tomorrow.

**Comment by steven-omaha** [comment]
Fixed in v1.4.2
