### ISSUE TITLE
Binary AUR package

### ISSUE THREAD

**Issue by thechubbypanda** [steven-omaha/pacdef#58]
Building the package every install/update is very time consuming. Building centrally and shipping a pacdef-bin package would be ideal. I'm happy to maintain the AUR package, just need somewhere to get the binaries.

**Comment by steven-omaha** [comment]
That's a good idea. I would like to automate this using github actions. 

Maintaining the AUR package is not a big deal, I can easily do this myself when I create a new release.

**Comment by thechubbypanda** [comment]
Awesome :)

If you'd like, I can contribute some actions stuff to automate it?
Are you thinking of automating releases as well or just building the binary?

**Comment by steven-omaha** [comment]
That would be great, and I'd highly appreciate it! 

It's just building the binary for Arch (`cargo build --release -F arch`) whenever there's a commit to main. I would still like to handle the releases manually.

If you'd like to give it a try, feel free to draft a PR. :)
