### ISSUE TITLE
[Feature request]: use $CARGO_HOME

### ISSUE THREAD

**Issue by danbluhmhansen** [steven-omaha/pacdef#70]
### In one sentence, what would the new feature allow the user to do?

Use the `$CARGO_HOME` environment variable for rust packages if set

### Describe what problem this new feature would solve.

I use the `$CARGO_HOME` environment variable to override the default `~/.cargo` directory, this variable is described here [Cargo Book - Environment Variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html). This causes `pacdef` to never find the `.crates2.json` file.

### How should this feature in your opinion work?

Prioritize `$CARGO_HOME` with a fallback to `$HOME/.cargo` when looking for the `.crates2.json` file.

### Would you be willing to implement this? We would support you through this process.

- [X] Yes, I would like to implement this.

### Additional information

I already have a pull request ready that I can open if that's alright.

**Comment by steven-omaha** [comment]
Thanks for the feature request. That would be great!

Please open a PR, I will probably get to reviewing it next week. 

Thank you for your contribution!
