### ISSUE TITLE
Single package is not recognized without newline

### ISSUE THREAD

**Issue by eh8** [steven-omaha/pacdef#9]
**Describe the bug**
When I create a group containing a single package, `pacdef` fails to detect said package if there not a newline at the end of the file.

**Affected version**
Output of `pacdef version`: `pacdef, version: 0.8.0`

Output of `python --version`: `Python 3.10.7`

**Operating System**
Arch Linux, x86_64

**To Reproduce**
1. Create a file `foo` containing a single package `bar`. Ensure there is no newline at the end of the file.
2. `pacdef import foo`
3. `pacdef sync` does not prompt the user to install `bar`.

**Expected behavior**
`pacdef` prompts the user to install `bar`.

**Comment by arctic-penguin** [comment]
Thank you for the report, and congrats on the first user-submitted bug report!

I have pushed a potential fix. Please install `pacdef-git`, and let me know if this fixes the issue.

**Comment by arctic-penguin** [comment]
Thank you for the bug report, and the first user-provided issue!

I have pushed a potential fix. Would you please try and confirm that `pacdef-git` fixes your issue?

**Comment by eh8** [comment]
Issue fixed! Thank you.
